### ISSUE TITLE
Score maps

### ISSUE THREAD

**Issue by fortminors** [graspnet/suctionnet-baseline#3]
Hello! Could you please point out the location of `score_maps` that are used during training? Where are they stored? I searched the repository and the [website](https://graspnet.net/suction), but haven't found anything.

Also, that would be great if you could explain what they represent and how are they collected. Thanks in advance!

**Comment by Fang-Haoshu** [comment]
Hi, I think you are looking for the  "seal/wrench label" on the website?

**Comment by fortminors** [comment]
@Fang-Haoshu Thank you for your reply. 
I was looking at the suctionnet_dataset.py script and found out that it is searching for some directory called `score_maps`
![image](https://user-images.githubusercontent.com/36015059/179353222-5c2a9d8a-9f61-4d63-93a1-1f835772f99f.png)

I later found `scores` in seal_label .npz files, but I am not sure that it is the same thing. To me, it looked like some links to files are missing. Please, correct me if I am wrong

**Comment by Fang-Haoshu** [comment]
Oh I see. You need to download the dataset from the website and then run https://github.com/graspnet/suctionnet-baseline#training-prerequisites to generate score_maps
