### ISSUE TITLE
is the checkpoint mentioned in file inference.py available?

### ISSUE THREAD

**Issue by kaixin-bai** [graspnet/suctionnet-baseline#6]
in the file `inference.py` there are lots of flags mentioned at the beginning, what the meaning of these? and where to download the checkpoint?

**Comment by hwcao17** [comment]
We only have models for deeplabv3_resnet101 and convnet_resnet101. Please see the shell files under https://github.com/graspnet/suctionnet-baseline/tree/master/neural_network/scripts. We provide download links for the pre-trained model in the readme file.
