### ISSUE TITLE
Specific camera model for the 'RealSense' in this repo

### ISSUE THREAD

**Issue by SonYeongGwang** [graspnet/suctionnet-baseline#7]
In this work, which camera (ex. D435) was used to build the dataset called 'RealSense'?

**Comment by hwcao17** [comment]
@Fang-Haoshu

**Comment by Fang-Haoshu** [comment]
Yes, it's D435

**Comment by L-Reichardt** [comment]
@Fang-Haoshu @hwcao17 
Could you provide the camera settings or define which sensor profile was used? Id like to set the filters the exact same way as used for data recording.
